# TASK : 1  
**PASSING LIST**

1. Convert a given Python list into a NumPy array and display its type

In [1]:
import numpy as np
lst=[1, 2, 3, 4, 5, 6, 7, 8]
numarr=np.array(lst)
print("Array: ",numarr)
print("Data Type: ",type(numarr))

Array:  [1 2 3 4 5 6 7 8]
Data Type:  <class 'numpy.ndarray'>


2. Convert a given Python nested list (matrix) into a NumPy array and display its properties.

In [2]:
mtrx=[[1, 2, 3],[4, 5, 6],[7, 8, 9]]
mtrx_arr=np.array(mtrx)
print("Array: ",mtrx_arr)
print("Array Shape: ",mtrx_arr.shape)
print("Data Type: ",type(mtrx_arr))

Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array Shape:  (3, 3)
Data Type:  <class 'numpy.ndarray'>


# TASK : 2  
**OPERATORS**

**ARANGE:**

1. Create a NumPy array containing numbers from 1 to 10 using the arange() function

In [3]:
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Using NumPy, generate an array of numbers starting from 1 up to 10 (inclusive) with a
step size of 2 using the arange() function.

In [4]:
arr2 = np.arange(1, 11, 2)
print(arr2)

[1 3 5 7 9]


**ZEROS AND ONES:**
1. Using NumPy, create a 1D array of size 3 filled with zeros using the zeros() function.

In [5]:
z_arr=np.zeros(3)
print("Zero Array: ",z_arr)

Zero Array:  [0. 0. 0.]


2. Create a 10x10 matrix filled with Ones using NumPy.

In [6]:
o_arr=np.ones((10,10))
print("Ones Array", o_arr)

Ones Array [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**LINSPACE:**

Using NumPy's linspace() function, generate an array of 25 evenly spaced numbers between 1
and 11, inclusive.

In [7]:
linspace_arr = np.linspace(1, 11, 25)
print(linspace_arr)

[ 1.          1.41666667  1.83333333  2.25        2.66666667  3.08333333
  3.5         3.91666667  4.33333333  4.75        5.16666667  5.58333333
  6.          6.41666667  6.83333333  7.25        7.66666667  8.08333333
  8.5         8.91666667  9.33333333  9.75       10.16666667 10.58333333
 11.        ]


**IDENTITY MATRIX:**

Using NumPy, create a 10x10 identity matrix where all the elements are zero except for the main
diagonal, which should contain ones.

In [8]:
identity = np.eye(10)
print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**RANDOM PACKAGE:**

Using NumPy, generate a 1D array of length 4 filled with random floating-point numbers
sampled from a uniform distribution over the interval [0, 1].


In [12]:
np.random.rand(4)

array([0.40441137, 0.73444996, 0.23767792, 0.36550554])

**RANDN:**

1. Using NumPy, generate a 1D array of length 2 filled with random floating-point numbers
sampled from a standard normal distribution (mean = 0, standard deviation = 1).

In [16]:
np.random.randn(2)

array([-0.43495893, -0.20938257])

2. Using NumPy, generate a 6x6 matrix filled with random floating-point numbers sampled from
a standard normal distribution (mean = 0, standard deviation = 1).

In [18]:
np.random.randn(6,6)

array([[-1.56280046, -0.18180075, -0.19690317,  0.99871611, -1.5746569 ,
         1.8544943 ],
       [ 0.86635605,  0.98980113,  2.19505271,  0.43397528, -1.57069004,
         1.48652191],
       [ 2.17547648,  0.83170394, -2.19043633, -0.9823739 , -0.72218718,
        -0.50432778],
       [ 1.32178117, -0.10809465,  0.36798025, -0.02243516,  0.78962127,
        -0.17332303],
       [-0.79283402,  0.47113931, -1.74874808,  1.5123481 ,  1.50958554,
         1.99325055],
       [-1.25305812, -0.71074224, -0.77766407,  0.62030303, -1.56589314,
        -0.56816118]])

**RANDINT:**

1.Using NumPy, generate a random integer between 1 and 5 (inclusive)

In [20]:
np.random.randint(1,6)

2

2.Using NumPy, generate a 1D array of 10 random integers, each ranging from 1 to 5 (inclusive).


In [21]:
np.random.randint(1,6,size=(10))

array([5, 1, 5, 1, 1, 2, 1, 5, 1, 5])

**ARRAY AND ATTRIBUTES**

**ARRAY:**

Using NumPy, create a 1D array containing 25 sequential integers starting from 0.

In [25]:
arr3=np.arange(25)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


**RANDOM:**

Using NumPy, generate a 1D array containing 10 random integers ranging from 0 to 49
(inclusive).


In [30]:
arr4=np.array(np.random.randint(0,50,size=10))
print(arr4)

[37 34 14 47 39 12 18 18 39 26]


**SHAPE:**

  Given a NumPy array a, determine its shape using the appropriate attribute

In [31]:
a=np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


**RESHAPE:**

Given a NumPy array a, reshape it into a 2x3 matrix.


In [36]:
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


**MINIMUM:**

Find the Minimum Value in a 1D Array

In [38]:
np.min(a)

1

# TASK : 2  
**ARGUMENT FUNCTION:**

Given a NumPy array r, determine the index of its maximum value using the appropriate
NumPy function.


In [41]:
np.argmax(a)

5

**SLICING:**

Given a NumPy array a, assign the value 1000 to the first five elements using slicing.


In [42]:
a[:5] = 1000
print(a)

[1000 1000 1000 1000 1000    6]


**INDEXING**

Create a 3x3 NumPy array named mat with the following structure:
[ [1, 2, 3],
[4, 5, 6],
[7, 8, 9] ]


Instructions:

● Use the appropriate NumPy function to create the specified 3x3 array.

● Assign this array to the variable mat.

● Print mat to verify its structure.


In [44]:
mat=np.array([ [1, 2, 3],[4, 5, 6],[7, 8, 9] ])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**ARITHMETIC OPERATORS**

You are required to follow the below the steps one by one and make each cell of a code:

● Create a one-dimensional NumPy array named c containing integers from 1 to 10
(inclusive).

● And then perform element wise Addition, Subtraction, Multiplication and Division of the
array with itself


In [48]:
c=np.arange(1,11)
print("Addition:", c + c)
print("Subtraction:", c - c)
print("Multiplication:", c * c)
print("Division:", c / c)

Addition: [ 2  4  6  8 10 12 14 16 18 20]
Subtraction: [0 0 0 0 0 0 0 0 0 0]
Multiplication: [  1   4   9  16  25  36  49  64  81 100]
Division: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**UNIVERSAL ARRAY:**

**ELEMENT-WISE ADDITION OF TWO ARRAY:**

**Task: Given two NumPy arrays, perform element-wise addition**

Instructions:

● Create two 1D NumPy arrays of the same length.

● Use the appropriate numpy function to add them element-wise.

● Print the resulting array.


In [53]:
d=np.arange(5)
e=np.arange(5,10)
np.add(d,e)

array([ 5,  7,  9, 11, 13])

**APPLYING TRIGONOMETRIC FUNCTION:**

**Apply the sine and cosine to an array of angles.**

Instructions:

● Create a 1D NumPy array containing angles in radians.

● Use appropriate numpy functions to compute the sine and cosine of each angle,
respectively.


In [55]:
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

sinv=np.sin(angles)
cosv=np.cos(angles)

print(f"Sin Values: {sinv}\nCos Values: {cosv}")

Sin Values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cos Values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


**EXPONENTIATION OF ARRAY ELEMENTS:**

**Raise each element of a NumPy array to a specified power**

Instructions:

● Create a 1D NumPy array with integer elements.

● Choose an integer exponent.

● Use the appropriate numpy function to raise each element of the array to the chosen
power.


In [57]:
f=np.arange(10)
ex=2
np.power(f, ex)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

**CALCULATING THE SQUARE ROOT OF ELEMENTS:**

**Compute the square root of each element in a NumPy array**


Instructions:

● Create a 1D NumPy array with non-negative numerical elements.

● Use the appropriate numpy function to calculate the square root of each element.


In [58]:
g=np.arange(10)
np.sqrt(g)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

**MATRIX MULTIPLICATION:**

**Perform element-wise multiplication of a 3x3 NumPy array mat with itself.**

Instructions:

Create a 3x3 NumPy array mat with the following structure:
[ [1, 2, 3],
[4, 5, 6],
[7, 8, 9] ]

● Multiply mat by itself element-wise.

● Print the resulting array

In [61]:
h=np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
np.dot(h,h)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])